"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.seeded_item import SeededItem
from openapi_client.model.status import Status
globals()['SeededItem'] = SeededItem
globals()['Status'] = Status
from openapi_client.model.organisation_seed_response import OrganisationSeedResponse


class TestOrganisationSeedResponse(unittest.TestCase):
    """OrganisationSeedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrganisationSeedResponse(self):
        """Test OrganisationSeedResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrganisationSeedResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
