"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.status import Status
globals()['Status'] = Status
from openapi_client.model.ui_schema_response import UiSchemaResponse


class TestUiSchemaResponse(unittest.TestCase):
    """UiSchemaResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUiSchemaResponse(self):
        """Test UiSchemaResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UiSchemaResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
