"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.item_category import ItemCategory
from openapi_client.model.item_sub_type import ItemSubType
globals()['ItemCategory'] = ItemCategory
globals()['ItemSubType'] = ItemSubType
from openapi_client.model.item_model import ItemModel


class TestItemModel(unittest.TestCase):
    """ItemModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItemModel(self):
        """Test ItemModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ItemModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
