"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.dataset_temporal_information import DatasetTemporalInformation
globals()['DatasetTemporalInformation'] = DatasetTemporalInformation
from rrap_mds_is_registry_api.model.temporal_information import TemporalInformation


class TestTemporalInformation(unittest.TestCase):
    """TemporalInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTemporalInformation(self):
        """Test TemporalInformation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TemporalInformation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
