"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.item_model_run import ItemModelRun
globals()['ItemModelRun'] = ItemModelRun
from rrap_mds_is_registry_api.model.items2 import Items2


class TestItems2(unittest.TestCase):
    """Items2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItems2(self):
        """Test Items2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Items2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
