"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.workflow_run_completion_status import WorkflowRunCompletionStatus


class TestWorkflowRunCompletionStatus(unittest.TestCase):
    """WorkflowRunCompletionStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkflowRunCompletionStatus(self):
        """Test WorkflowRunCompletionStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkflowRunCompletionStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
