"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.item_organisation import ItemOrganisation
from openapi_client.model.status import Status
globals()['ItemOrganisation'] = ItemOrganisation
globals()['Status'] = Status
from openapi_client.model.organisation_create_response import OrganisationCreateResponse


class TestOrganisationCreateResponse(unittest.TestCase):
    """OrganisationCreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrganisationCreateResponse(self):
        """Test OrganisationCreateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrganisationCreateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
