"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.item6 import Item6


class TestItem6(unittest.TestCase):
    """Item6 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItem6(self):
        """Test Item6"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Item6()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
