"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.item6 import Item6
from rrap_mds_is_registry_api.model.status import Status
globals()['Item6'] = Item6
globals()['Status'] = Status
from rrap_mds_is_registry_api.model.untyped_fetch_response import UntypedFetchResponse


class TestUntypedFetchResponse(unittest.TestCase):
    """UntypedFetchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUntypedFetchResponse(self):
        """Test UntypedFetchResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UntypedFetchResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
