"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.seeded_item import SeededItem
from openapi_client.model.status import Status
globals()['SeededItem'] = SeededItem
globals()['Status'] = Status
from openapi_client.model.model_run_workflow_definition_seed_response import ModelRunWorkflowDefinitionSeedResponse


class TestModelRunWorkflowDefinitionSeedResponse(unittest.TestCase):
    """ModelRunWorkflowDefinitionSeedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelRunWorkflowDefinitionSeedResponse(self):
        """Test ModelRunWorkflowDefinitionSeedResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelRunWorkflowDefinitionSeedResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
