"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.item_sub_type import ItemSubType
globals()['ItemSubType'] = ItemSubType
from rrap_mds_is_registry_api.model.query_filter_item_subtype import QueryFilterItemSubtype


class TestQueryFilterItemSubtype(unittest.TestCase):
    """QueryFilterItemSubtype unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueryFilterItemSubtype(self):
        """Test QueryFilterItemSubtype"""
        # FIXME: construct object with mandatory attributes with example values
        # model = QueryFilterItemSubtype()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
