"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.model_run_record import ModelRunRecord
from rrap_mds_is_registry_api.model.workflow_run_completion_status import WorkflowRunCompletionStatus
globals()['ModelRunRecord'] = ModelRunRecord
globals()['WorkflowRunCompletionStatus'] = WorkflowRunCompletionStatus
from rrap_mds_is_registry_api.model.model_run_domain_info import ModelRunDomainInfo


class TestModelRunDomainInfo(unittest.TestCase):
    """ModelRunDomainInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelRunDomainInfo(self):
        """Test ModelRunDomainInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelRunDomainInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
