"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.item_organisation import ItemOrganisation
from rrap_mds_is_registry_api.model.record_type import RecordType
from rrap_mds_is_registry_api.model.ror import Ror
globals()['ItemOrganisation'] = ItemOrganisation
globals()['RecordType'] = RecordType
globals()['Ror'] = Ror
from rrap_mds_is_registry_api.model.created_item4 import CreatedItem4


class TestCreatedItem4(unittest.TestCase):
    """CreatedItem4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreatedItem4(self):
        """Test CreatedItem4"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreatedItem4()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
