"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.api.model_run_workflow_definition_api import ModelRunWorkflowDefinitionApi  # noqa: E501


class TestModelRunWorkflowDefinitionApi(unittest.TestCase):
    """ModelRunWorkflowDefinitionApi unit test stubs"""

    def setUp(self):
        self.api = ModelRunWorkflowDefinitionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_item_registry_entity_model_run_workflow_create_post(self):
        """Test case for create_item_registry_entity_model_run_workflow_create_post

        Create Item  # noqa: E501
        """
        pass

    def test_delete_item_registry_entity_model_run_workflow_delete_delete(self):
        """Test case for delete_item_registry_entity_model_run_workflow_delete_delete

        Delete Item  # noqa: E501
        """
        pass

    def test_fetch_item_registry_entity_model_run_workflow_fetch_get(self):
        """Test case for fetch_item_registry_entity_model_run_workflow_fetch_get

        Fetch Item  # noqa: E501
        """
        pass

    def test_get_schema_registry_entity_model_run_workflow_schema_get(self):
        """Test case for get_schema_registry_entity_model_run_workflow_schema_get

        Get Schema  # noqa: E501
        """
        pass

    def test_get_ui_schema_registry_entity_model_run_workflow_ui_schema_get(self):
        """Test case for get_ui_schema_registry_entity_model_run_workflow_ui_schema_get

        Get Ui Schema  # noqa: E501
        """
        pass

    def test_list_items_registry_entity_model_run_workflow_list_get(self):
        """Test case for list_items_registry_entity_model_run_workflow_list_get

        List Items  # noqa: E501
        """
        pass

    def test_seed_item_registry_entity_model_run_workflow_seed_post(self):
        """Test case for seed_item_registry_entity_model_run_workflow_seed_post

        Seed Item  # noqa: E501
        """
        pass

    def test_update_item_registry_entity_model_run_workflow_update_put(self):
        """Test case for update_item_registry_entity_model_run_workflow_update_put

        Update Item  # noqa: E501
        """
        pass

    def test_validate_registry_entity_model_run_workflow_validate_post(self):
        """Test case for validate_registry_entity_model_run_workflow_validate_post

        Validate  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
