"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.item_category import ItemCategory
from rrap_mds_is_registry_api.model.item_person import ItemPerson
from rrap_mds_is_registry_api.model.item_sub_type import ItemSubType
from rrap_mds_is_registry_api.model.orcid import Orcid
from rrap_mds_is_registry_api.model.record_type import RecordType
from rrap_mds_is_registry_api.model.seeded_item import SeededItem
globals()['ItemCategory'] = ItemCategory
globals()['ItemPerson'] = ItemPerson
globals()['ItemSubType'] = ItemSubType
globals()['Orcid'] = Orcid
globals()['RecordType'] = RecordType
globals()['SeededItem'] = SeededItem
from rrap_mds_is_registry_api.model.item5 import Item5


class TestItem5(unittest.TestCase):
    """Item5 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItem5(self):
        """Test Item5"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Item5()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
