"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.dataset_structural_template import DatasetStructuralTemplate
from openapi_client.model.dataset_temporal_information import DatasetTemporalInformation
from openapi_client.model.dataset_usage_information import DatasetUsageInformation
from openapi_client.model.item_category import ItemCategory
from openapi_client.model.item_dataset_template import ItemDatasetTemplate
from openapi_client.model.item_sub_type import ItemSubType
from openapi_client.model.seeded_item import SeededItem
globals()['DatasetStructuralTemplate'] = DatasetStructuralTemplate
globals()['DatasetTemporalInformation'] = DatasetTemporalInformation
globals()['DatasetUsageInformation'] = DatasetUsageInformation
globals()['ItemCategory'] = ItemCategory
globals()['ItemDatasetTemplate'] = ItemDatasetTemplate
globals()['ItemSubType'] = ItemSubType
globals()['SeededItem'] = SeededItem
from openapi_client.model.item import Item


class TestItem(unittest.TestCase):
    """Item unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItem(self):
        """Test Item"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Item()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
