"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.item2 import Item2
from openapi_client.model.status import Status
globals()['Item2'] = Item2
globals()['Status'] = Status
from openapi_client.model.model_run_fetch_response import ModelRunFetchResponse


class TestModelRunFetchResponse(unittest.TestCase):
    """ModelRunFetchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelRunFetchResponse(self):
        """Test ModelRunFetchResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelRunFetchResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
