"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.association_info import AssociationInfo
from openapi_client.model.input_info import InputInfo
from openapi_client.model.model_run_workflow_definition_resource import ModelRunWorkflowDefinitionResource
from openapi_client.model.output_info import OutputInfo
globals()['AssociationInfo'] = AssociationInfo
globals()['InputInfo'] = InputInfo
globals()['ModelRunWorkflowDefinitionResource'] = ModelRunWorkflowDefinitionResource
globals()['OutputInfo'] = OutputInfo
from openapi_client.model.model_run_record import ModelRunRecord


class TestModelRunRecord(unittest.TestCase):
    """ModelRunRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelRunRecord(self):
        """Test ModelRunRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelRunRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
