"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.person_api import PersonApi  # noqa: E501


class TestPersonApi(unittest.TestCase):
    """PersonApi unit test stubs"""

    def setUp(self):
        self.api = PersonApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_agent_person(self):
        """Test case for create_agent_person

        Create Item  # noqa: E501
        """
        pass

    def test_delete_agent_person(self):
        """Test case for delete_agent_person

        Delete Item  # noqa: E501
        """
        pass

    def test_fetch_agent_person(self):
        """Test case for fetch_agent_person

        Fetch Item  # noqa: E501
        """
        pass

    def test_list_agent_person(self):
        """Test case for list_agent_person

        List Items  # noqa: E501
        """
        pass

    def test_schema_agent_person(self):
        """Test case for schema_agent_person

        Get Schema  # noqa: E501
        """
        pass

    def test_seed_agent_person(self):
        """Test case for seed_agent_person

        Seed Item  # noqa: E501
        """
        pass

    def test_ui_schema_agent_person(self):
        """Test case for ui_schema_agent_person

        Get Ui Schema  # noqa: E501
        """
        pass

    def test_update_agent_person(self):
        """Test case for update_agent_person

        Update Item  # noqa: E501
        """
        pass

    def test_validate_agent_person(self):
        """Test case for validate_agent_person

        Validate  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
