"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.item_model_run_workflow_definition import ItemModelRunWorkflowDefinition
globals()['ItemModelRunWorkflowDefinition'] = ItemModelRunWorkflowDefinition
from rrap_mds_is_registry_api.model.items3 import Items3


class TestItems3(unittest.TestCase):
    """Items3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItems3(self):
        """Test Items3"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Items3()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
