"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.items6 import Items6
from rrap_mds_is_registry_api.model.status import Status
from rrap_mds_is_registry_api.model.total_item_count import TotalItemCount
globals()['Items6'] = Items6
globals()['Status'] = Status
globals()['TotalItemCount'] = TotalItemCount
from rrap_mds_is_registry_api.model.unparsed_list_response import UnparsedListResponse


class TestUnparsedListResponse(unittest.TestCase):
    """UnparsedListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnparsedListResponse(self):
        """Test UnparsedListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UnparsedListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
