"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.failure_list import FailureList
from rrap_mds_is_registry_api.model.statistics import Statistics
from rrap_mds_is_registry_api.model.status import Status
globals()['FailureList'] = FailureList
globals()['Statistics'] = Statistics
globals()['Status'] = Status
from rrap_mds_is_registry_api.model.registry_import_response import RegistryImportResponse


class TestRegistryImportResponse(unittest.TestCase):
    """RegistryImportResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRegistryImportResponse(self):
        """Test RegistryImportResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RegistryImportResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
