"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.items6 import Items6


class TestItems6(unittest.TestCase):
    """Items6 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItems6(self):
        """Test Items6"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Items6()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
