"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.import_mode import ImportMode
globals()['ImportMode'] = ImportMode
from rrap_mds_is_registry_api.model.registry_import_request import RegistryImportRequest


class TestRegistryImportRequest(unittest.TestCase):
    """RegistryImportRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRegistryImportRequest(self):
        """Test RegistryImportRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RegistryImportRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
