"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.item_category import ItemCategory
from rrap_mds_is_registry_api.model.item_model_run import ItemModelRun
from rrap_mds_is_registry_api.model.item_sub_type import ItemSubType
from rrap_mds_is_registry_api.model.model_run_record import ModelRunRecord
from rrap_mds_is_registry_api.model.record_type import RecordType
from rrap_mds_is_registry_api.model.seeded_item import SeededItem
from rrap_mds_is_registry_api.model.workflow_run_completion_status import WorkflowRunCompletionStatus
globals()['ItemCategory'] = ItemCategory
globals()['ItemModelRun'] = ItemModelRun
globals()['ItemSubType'] = ItemSubType
globals()['ModelRunRecord'] = ModelRunRecord
globals()['RecordType'] = RecordType
globals()['SeededItem'] = SeededItem
globals()['WorkflowRunCompletionStatus'] = WorkflowRunCompletionStatus
from rrap_mds_is_registry_api.model.item2 import Item2


class TestItem2(unittest.TestCase):
    """Item2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItem2(self):
        """Test Item2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Item2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
