"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.item1 import Item1
from rrap_mds_is_registry_api.model.item_is_seed import ItemIsSeed
from rrap_mds_is_registry_api.model.status import Status
globals()['Item1'] = Item1
globals()['ItemIsSeed'] = ItemIsSeed
globals()['Status'] = Status
from rrap_mds_is_registry_api.model.model_fetch_response import ModelFetchResponse


class TestModelFetchResponse(unittest.TestCase):
    """ModelFetchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelFetchResponse(self):
        """Test ModelFetchResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelFetchResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
