"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.model_run_workflow_definition_api import ModelRunWorkflowDefinitionApi  # noqa: E501


class TestModelRunWorkflowDefinitionApi(unittest.TestCase):
    """ModelRunWorkflowDefinitionApi unit test stubs"""

    def setUp(self):
        self.api = ModelRunWorkflowDefinitionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_entity_model_run_workflow_definition(self):
        """Test case for create_entity_model_run_workflow_definition

        Create Item  # noqa: E501
        """
        pass

    def test_delete_entity_model_run_workflow_definition(self):
        """Test case for delete_entity_model_run_workflow_definition

        Delete Item  # noqa: E501
        """
        pass

    def test_fetch_entity_model_run_workflow_definition(self):
        """Test case for fetch_entity_model_run_workflow_definition

        Fetch Item  # noqa: E501
        """
        pass

    def test_list_entity_model_run_workflow_definition(self):
        """Test case for list_entity_model_run_workflow_definition

        List Items  # noqa: E501
        """
        pass

    def test_schema_entity_model_run_workflow_definition(self):
        """Test case for schema_entity_model_run_workflow_definition

        Get Schema  # noqa: E501
        """
        pass

    def test_seed_entity_model_run_workflow_definition(self):
        """Test case for seed_entity_model_run_workflow_definition

        Seed Item  # noqa: E501
        """
        pass

    def test_ui_schema_entity_model_run_workflow_definition(self):
        """Test case for ui_schema_entity_model_run_workflow_definition

        Get Ui Schema  # noqa: E501
        """
        pass

    def test_update_entity_model_run_workflow_definition(self):
        """Test case for update_entity_model_run_workflow_definition

        Update Item  # noqa: E501
        """
        pass

    def test_validate_entity_model_run_workflow_definition(self):
        """Test case for validate_entity_model_run_workflow_definition

        Validate  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
