"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.item_model import ItemModel
from rrap_mds_is_registry_api.model.seeded_item import SeededItem
from rrap_mds_is_registry_api.model.status import Status
globals()['ItemModel'] = ItemModel
globals()['SeededItem'] = SeededItem
globals()['Status'] = Status
from rrap_mds_is_registry_api.model.model_list_response import ModelListResponse


class TestModelListResponse(unittest.TestCase):
    """ModelListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelListResponse(self):
        """Test ModelListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
