"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.api.general_registry_api import GeneralRegistryApi  # noqa: E501


class TestGeneralRegistryApi(unittest.TestCase):
    """GeneralRegistryApi unit test stubs"""

    def setUp(self):
        self.api = GeneralRegistryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fetch(self):
        """Test case for fetch

        Fetch Item  # noqa: E501
        """
        pass

    def test_list(self):
        """Test case for list

        List Items  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
