"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.item_model import ItemModel
from rrap_mds_is_registry_api.model.record_type import RecordType
globals()['ItemModel'] = ItemModel
globals()['RecordType'] = RecordType
from rrap_mds_is_registry_api.model.created_item1 import CreatedItem1


class TestCreatedItem1(unittest.TestCase):
    """CreatedItem1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreatedItem1(self):
        """Test CreatedItem1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreatedItem1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
