"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.dataset_parameter import DatasetParameter
from rrap_mds_is_registry_api.model.dataset_usage_information import DatasetUsageInformation
globals()['DatasetParameter'] = DatasetParameter
globals()['DatasetUsageInformation'] = DatasetUsageInformation
from rrap_mds_is_registry_api.model.file_information import FileInformation


class TestFileInformation(unittest.TestCase):
    """FileInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileInformation(self):
        """Test FileInformation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FileInformation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
