"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.item_model_run import ItemModelRun
from openapi_client.model.status import Status
globals()['ItemModelRun'] = ItemModelRun
globals()['Status'] = Status
from openapi_client.model.model_run_create_response import ModelRunCreateResponse


class TestModelRunCreateResponse(unittest.TestCase):
    """ModelRunCreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelRunCreateResponse(self):
        """Test ModelRunCreateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelRunCreateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
