"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.model_run_api import ModelRunApi  # noqa: E501


class TestModelRunApi(unittest.TestCase):
    """ModelRunApi unit test stubs"""

    def setUp(self):
        self.api = ModelRunApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_activity_model_run(self):
        """Test case for create_activity_model_run

        Create Item  # noqa: E501
        """
        pass

    def test_delete_activity_model_run(self):
        """Test case for delete_activity_model_run

        Delete Item  # noqa: E501
        """
        pass

    def test_fetch_activity_model_run(self):
        """Test case for fetch_activity_model_run

        Fetch Item  # noqa: E501
        """
        pass

    def test_list_activity_model_run(self):
        """Test case for list_activity_model_run

        List Items  # noqa: E501
        """
        pass

    def test_schema_activity_model_run(self):
        """Test case for schema_activity_model_run

        Get Schema  # noqa: E501
        """
        pass

    def test_seed_activity_model_run(self):
        """Test case for seed_activity_model_run

        Seed Item  # noqa: E501
        """
        pass

    def test_ui_schema_activity_model_run(self):
        """Test case for ui_schema_activity_model_run

        Get Ui Schema  # noqa: E501
        """
        pass

    def test_update_activity_model_run(self):
        """Test case for update_activity_model_run

        Update Item  # noqa: E501
        """
        pass

    def test_validate_activity_model_run(self):
        """Test case for validate_activity_model_run

        Validate  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
