"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.email import Email


class TestEmail(unittest.TestCase):
    """Email unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmail(self):
        """Test Email"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Email()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
