"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.item_model_run_workflow_definition import ItemModelRunWorkflowDefinition
from rrap_mds_is_registry_api.model.seeded_item import SeededItem
from rrap_mds_is_registry_api.model.status import Status
globals()['ItemModelRunWorkflowDefinition'] = ItemModelRunWorkflowDefinition
globals()['SeededItem'] = SeededItem
globals()['Status'] = Status
from rrap_mds_is_registry_api.model.model_run_workflow_definition_list_response import ModelRunWorkflowDefinitionListResponse


class TestModelRunWorkflowDefinitionListResponse(unittest.TestCase):
    """ModelRunWorkflowDefinitionListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelRunWorkflowDefinitionListResponse(self):
        """Test ModelRunWorkflowDefinitionListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelRunWorkflowDefinitionListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
