"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.import_mode import ImportMode
globals()['ImportMode'] = ImportMode
from rrap_mds_is_registry_api.model.registry_restore_request import RegistryRestoreRequest


class TestRegistryRestoreRequest(unittest.TestCase):
    """RegistryRestoreRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRegistryRestoreRequest(self):
        """Test RegistryRestoreRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RegistryRestoreRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
