"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.item_person import ItemPerson
from rrap_mds_is_registry_api.model.orcid import Orcid
from rrap_mds_is_registry_api.model.record_type import RecordType
globals()['ItemPerson'] = ItemPerson
globals()['Orcid'] = Orcid
globals()['RecordType'] = RecordType
from rrap_mds_is_registry_api.model.created_item5 import CreatedItem5


class TestCreatedItem5(unittest.TestCase):
    """CreatedItem5 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreatedItem5(self):
        """Test CreatedItem5"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreatedItem5()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
