"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.items6 import Items6
from rrap_mds_is_registry_api.model.status import Status
globals()['Items6'] = Items6
globals()['Status'] = Status
from rrap_mds_is_registry_api.model.registry_export_response import RegistryExportResponse


class TestRegistryExportResponse(unittest.TestCase):
    """RegistryExportResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRegistryExportResponse(self):
        """Test RegistryExportResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RegistryExportResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
