"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.created_item5 import CreatedItem5
from rrap_mds_is_registry_api.model.status import Status
globals()['CreatedItem5'] = CreatedItem5
globals()['Status'] = Status
from rrap_mds_is_registry_api.model.person_create_response import PersonCreateResponse


class TestPersonCreateResponse(unittest.TestCase):
    """PersonCreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPersonCreateResponse(self):
        """Test PersonCreateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PersonCreateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
