"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.description import Description
from rrap_mds_is_registry_api.model.enforce_constraints import EnforceConstraints
from rrap_mds_is_registry_api.model.enforce_size_constraints import EnforceSizeConstraints
from rrap_mds_is_registry_api.model.extension import Extension
from rrap_mds_is_registry_api.model.folder import Folder
from rrap_mds_is_registry_api.model.parameters import Parameters
from rrap_mds_is_registry_api.model.path import Path
from rrap_mds_is_registry_api.model.size_estimate import SizeEstimate
from rrap_mds_is_registry_api.model.size_max import SizeMax
from rrap_mds_is_registry_api.model.size_min import SizeMin
from rrap_mds_is_registry_api.model.usage import Usage
globals()['Description'] = Description
globals()['EnforceConstraints'] = EnforceConstraints
globals()['EnforceSizeConstraints'] = EnforceSizeConstraints
globals()['Extension'] = Extension
globals()['Folder'] = Folder
globals()['Parameters'] = Parameters
globals()['Path'] = Path
globals()['SizeEstimate'] = SizeEstimate
globals()['SizeMax'] = SizeMax
globals()['SizeMin'] = SizeMin
globals()['Usage'] = Usage
from rrap_mds_is_registry_api.model.file_information import FileInformation


class TestFileInformation(unittest.TestCase):
    """FileInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileInformation(self):
        """Test FileInformation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FileInformation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
