"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.item_model_run_workflow_definition import ItemModelRunWorkflowDefinition
from openapi_client.model.status import Status
globals()['ItemModelRunWorkflowDefinition'] = ItemModelRunWorkflowDefinition
globals()['Status'] = Status
from openapi_client.model.model_run_workflow_definition_create_response import ModelRunWorkflowDefinitionCreateResponse


class TestModelRunWorkflowDefinitionCreateResponse(unittest.TestCase):
    """ModelRunWorkflowDefinitionCreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelRunWorkflowDefinitionCreateResponse(self):
        """Test ModelRunWorkflowDefinitionCreateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelRunWorkflowDefinitionCreateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
