"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.modeller_resource import ModellerResource
from openapi_client.model.organisation_resource import OrganisationResource
globals()['ModellerResource'] = ModellerResource
globals()['OrganisationResource'] = OrganisationResource
from openapi_client.model.association_info import AssociationInfo


class TestAssociationInfo(unittest.TestCase):
    """AssociationInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssociationInfo(self):
        """Test AssociationInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AssociationInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
