"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.complete_item_count import CompleteItemCount
from rrap_mds_is_registry_api.model.items4 import Items4
from rrap_mds_is_registry_api.model.seed_item_count import SeedItemCount
from rrap_mds_is_registry_api.model.seed_items import SeedItems
from rrap_mds_is_registry_api.model.status import Status
from rrap_mds_is_registry_api.model.total_item_count import TotalItemCount
from rrap_mds_is_registry_api.model.unparsable_item_count import UnparsableItemCount
from rrap_mds_is_registry_api.model.unparsable_items import UnparsableItems
globals()['CompleteItemCount'] = CompleteItemCount
globals()['Items4'] = Items4
globals()['SeedItemCount'] = SeedItemCount
globals()['SeedItems'] = SeedItems
globals()['Status'] = Status
globals()['TotalItemCount'] = TotalItemCount
globals()['UnparsableItemCount'] = UnparsableItemCount
globals()['UnparsableItems'] = UnparsableItems
from rrap_mds_is_registry_api.model.organisation_list_response import OrganisationListResponse


class TestOrganisationListResponse(unittest.TestCase):
    """OrganisationListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrganisationListResponse(self):
        """Test OrganisationListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrganisationListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
