"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.items7 import Items7


class TestItems7(unittest.TestCase):
    """Items7 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItems7(self):
        """Test Items7"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Items7()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
