"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.item_category import ItemCategory
from openapi_client.model.item_model import ItemModel
from openapi_client.model.item_sub_type import ItemSubType
from openapi_client.model.seeded_item import SeededItem
globals()['ItemCategory'] = ItemCategory
globals()['ItemModel'] = ItemModel
globals()['ItemSubType'] = ItemSubType
globals()['SeededItem'] = SeededItem
from openapi_client.model.item1 import Item1


class TestItem1(unittest.TestCase):
    """Item1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItem1(self):
        """Test Item1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Item1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
