"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.automation_schedule import AutomationSchedule
from rrap_mds_is_registry_api.model.version import Version
globals()['AutomationSchedule'] = AutomationSchedule
globals()['Version'] = Version
from rrap_mds_is_registry_api.model.model_run_workflow_definition_domain_info import ModelRunWorkflowDefinitionDomainInfo


class TestModelRunWorkflowDefinitionDomainInfo(unittest.TestCase):
    """ModelRunWorkflowDefinitionDomainInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelRunWorkflowDefinitionDomainInfo(self):
        """Test ModelRunWorkflowDefinitionDomainInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelRunWorkflowDefinitionDomainInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
