"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.query_filter_item_category import QueryFilterItemCategory
from rrap_mds_is_registry_api.model.query_filter_item_subtype import QueryFilterItemSubtype
globals()['QueryFilterItemCategory'] = QueryFilterItemCategory
globals()['QueryFilterItemSubtype'] = QueryFilterItemSubtype
from rrap_mds_is_registry_api.model.query_filter import QueryFilter


class TestQueryFilter(unittest.TestCase):
    """QueryFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueryFilter(self):
        """Test QueryFilter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = QueryFilter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
