"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.item_organisation import ItemOrganisation
globals()['ItemOrganisation'] = ItemOrganisation
from rrap_mds_is_registry_api.model.items4 import Items4


class TestItems4(unittest.TestCase):
    """Items4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItems4(self):
        """Test Items4"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Items4()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
