"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.api.model_api import ModelApi  # noqa: E501


class TestModelApi(unittest.TestCase):
    """ModelApi unit test stubs"""

    def setUp(self):
        self.api = ModelApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_entity_model(self):
        """Test case for create_entity_model

        Create Item  # noqa: E501
        """
        pass

    def test_delete_entity_model(self):
        """Test case for delete_entity_model

        Delete Item  # noqa: E501
        """
        pass

    def test_fetch_entity_model(self):
        """Test case for fetch_entity_model

        Fetch Item  # noqa: E501
        """
        pass

    def test_list_entity_model(self):
        """Test case for list_entity_model

        List Items  # noqa: E501
        """
        pass

    def test_schema_entity_model(self):
        """Test case for schema_entity_model

        Get Schema  # noqa: E501
        """
        pass

    def test_seed_entity_model(self):
        """Test case for seed_entity_model

        Seed Item  # noqa: E501
        """
        pass

    def test_ui_schema_entity_model(self):
        """Test case for ui_schema_entity_model

        Get Ui Schema  # noqa: E501
        """
        pass

    def test_update_entity_model(self):
        """Test case for update_entity_model

        Update Item  # noqa: E501
        """
        pass

    def test_validate_entity_model(self):
        """Test case for validate_entity_model

        Validate  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
