"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.item5 import Item5
from openapi_client.model.status import Status
globals()['Item5'] = Item5
globals()['Status'] = Status
from openapi_client.model.person_fetch_response import PersonFetchResponse


class TestPersonFetchResponse(unittest.TestCase):
    """PersonFetchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPersonFetchResponse(self):
        """Test PersonFetchResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PersonFetchResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
