"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.automation_schedule import AutomationSchedule
from rrap_mds_is_registry_api.model.record_type import RecordType
from rrap_mds_is_registry_api.model.version import Version
globals()['AutomationSchedule'] = AutomationSchedule
globals()['RecordType'] = RecordType
globals()['Version'] = Version
from rrap_mds_is_registry_api.model.item_model_run_workflow_definition import ItemModelRunWorkflowDefinition


class TestItemModelRunWorkflowDefinition(unittest.TestCase):
    """ItemModelRunWorkflowDefinition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItemModelRunWorkflowDefinition(self):
        """Test ItemModelRunWorkflowDefinition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ItemModelRunWorkflowDefinition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
