"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.item_person import ItemPerson
globals()['ItemPerson'] = ItemPerson
from rrap_mds_is_registry_api.model.items5 import Items5


class TestItems5(unittest.TestCase):
    """Items5 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItems5(self):
        """Test Items5"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Items5()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
