"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.item_category import ItemCategory
globals()['ItemCategory'] = ItemCategory
from rrap_mds_is_registry_api.model.query_filter_item_category import QueryFilterItemCategory


class TestQueryFilterItemCategory(unittest.TestCase):
    """QueryFilterItemCategory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueryFilterItemCategory(self):
        """Test QueryFilterItemCategory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = QueryFilterItemCategory()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
