"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.column_name import ColumnName


class TestColumnName(unittest.TestCase):
    """ColumnName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testColumnName(self):
        """Test ColumnName"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ColumnName()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
