"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.item_category import ItemCategory
from rrap_mds_is_registry_api.model.item_organisation import ItemOrganisation
from rrap_mds_is_registry_api.model.item_sub_type import ItemSubType
from rrap_mds_is_registry_api.model.seeded_item import SeededItem
globals()['ItemCategory'] = ItemCategory
globals()['ItemOrganisation'] = ItemOrganisation
globals()['ItemSubType'] = ItemSubType
globals()['SeededItem'] = SeededItem
from rrap_mds_is_registry_api.model.item4 import Item4


class TestItem4(unittest.TestCase):
    """Item4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItem4(self):
        """Test Item4"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Item4()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
