"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.additional_description import AdditionalDescription
from rrap_mds_is_registry_api.model.dataset_structural_template import DatasetStructuralTemplate
from rrap_mds_is_registry_api.model.file_information import FileInformation
globals()['AdditionalDescription'] = AdditionalDescription
globals()['DatasetStructuralTemplate'] = DatasetStructuralTemplate
globals()['FileInformation'] = FileInformation
from rrap_mds_is_registry_api.model.structural_template import StructuralTemplate


class TestStructuralTemplate(unittest.TestCase):
    """StructuralTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStructuralTemplate(self):
        """Test StructuralTemplate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StructuralTemplate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
