"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.api.organisation_api import OrganisationApi  # noqa: E501


class TestOrganisationApi(unittest.TestCase):
    """OrganisationApi unit test stubs"""

    def setUp(self):
        self.api = OrganisationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_agent_organisation(self):
        """Test case for create_agent_organisation

        Create Item  # noqa: E501
        """
        pass

    def test_delete_agent_organisation(self):
        """Test case for delete_agent_organisation

        Delete Item  # noqa: E501
        """
        pass

    def test_fetch_agent_organisation(self):
        """Test case for fetch_agent_organisation

        Fetch Item  # noqa: E501
        """
        pass

    def test_list_agent_organisation(self):
        """Test case for list_agent_organisation

        List Items  # noqa: E501
        """
        pass

    def test_schema_agent_organisation(self):
        """Test case for schema_agent_organisation

        Get Schema  # noqa: E501
        """
        pass

    def test_seed_agent_organisation(self):
        """Test case for seed_agent_organisation

        Seed Item  # noqa: E501
        """
        pass

    def test_ui_schema_agent_organisation(self):
        """Test case for ui_schema_agent_organisation

        Get Ui Schema  # noqa: E501
        """
        pass

    def test_update_agent_organisation(self):
        """Test case for update_agent_organisation

        Update Item  # noqa: E501
        """
        pass

    def test_validate_agent_organisation(self):
        """Test case for validate_agent_organisation

        Validate  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
