"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.created_item1 import CreatedItem1
from rrap_mds_is_registry_api.model.status import Status
globals()['CreatedItem1'] = CreatedItem1
globals()['Status'] = Status
from rrap_mds_is_registry_api.model.model_create_response import ModelCreateResponse


class TestModelCreateResponse(unittest.TestCase):
    """ModelCreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelCreateResponse(self):
        """Test ModelCreateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelCreateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
