"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.complete_item_count import CompleteItemCount


class TestCompleteItemCount(unittest.TestCase):
    """CompleteItemCount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompleteItemCount(self):
        """Test CompleteItemCount"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CompleteItemCount()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
