"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_registry_api
from rrap_mds_is_registry_api.model.size_max import SizeMax


class TestSizeMax(unittest.TestCase):
    """SizeMax unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSizeMax(self):
        """Test SizeMax"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SizeMax()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
