"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.templated_dataset import TemplatedDataset
globals()['TemplatedDataset'] = TemplatedDataset
from openapi_client.model.input_info import InputInfo


class TestInputInfo(unittest.TestCase):
    """InputInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInputInfo(self):
        """Test InputInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InputInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
